[package]
name = "backend-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async = "0.0.2"
axum = "0.6.1"
tokio = { version = "1.23.0", features = ["full"] }
